routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome-bootstrap');
});
Route::get('/welcome-default', function () {
    return view('welcome');
});

Route::prefix('dashboard')->name('dashboard.')->middleware(['auth'])->group(function () {
    Route::get('/', [\App\Http\Controllers\DashboardController::class, 'index'])->name('home');

    Route::prefix('product')->name('product.')->group(function () {
        Route::get('/', [\App\Http\Controllers\ProductController::class, 'index'])->name('home');
        Route::get('/create', [\App\Http\Controllers\ProductController::class, 'create'])->name('create');
        Route::post('/store', [\App\Http\Controllers\ProductController::class, 'store'])->name('store');
        Route::prefix('{product}')->group(function () {
            Route::get('/', [\App\Http\Controllers\ProductController::class, 'show'])->name('show');
            Route::get('/edit', [\App\Http\Controllers\ProductController::class, 'edit'])->name('edit');
            Route::put('/edit', [\App\Http\Controllers\ProductController::class, 'update'])->name('update');
            Route::delete('/delete', [\App\Http\Controllers\ProductController::class, 'destroy'])->name('delete');
            Route::get('/create-inventory', [\App\Http\Controllers\ProductController::class, 'createInventory'])->name('create-inventory');
            Route::post('/store-inventory', [\App\Http\Controllers\ProductController::class, 'storeInventory'])->name('store-inventory');
        });
    });

    Route::prefix('inventory')->name('inventory.')->group(function () {
        Route::get('/{reset?}', [\App\Http\Controllers\InventoryController::class, 'index'])->name('home');
        Route::post('/', [\App\Http\Controllers\InventoryController::class, 'search'])->name('search');
        Route::post('/reset', [\App\Http\Controllers\InventoryController::class, 'searchReset'])->name('search-reset');
        Route::prefix('{inventory}')->group(function () {
            Route::get('/edit', [\App\Http\Controllers\InventoryController::class, 'edit'])->name('edit');
            Route::put('/edit', [\App\Http\Controllers\InventoryController::class, 'update'])->name('update');
            Route::delete('/delete', [\App\Http\Controllers\InventoryController::class, 'destroy'])->name('delete');
        });
    });

});

require __DIR__.'/auth.php';

app/Models/Inventory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    use HasFactory;

    public function product()
    {

        return $this->belongsTo(
            Product::class,
            'product_id',
            'id'
        );

    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            return view('dashboard.home')
                ->with(
                    compact(
                        [
                            'user'
                        ]
                    )
                );

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\InventoryUpdateRequest;
use App\Models\Inventory;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Session;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($reset = null)
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            if(!empty($reset) AND $reset == 'reset') {

                Session()->forget(['query', 'quantity_limit']);

            }

            $user = Auth::user();

            if(!empty(Session::get('query')) OR !empty(Session::get('quantity_limit'))) {

                $session = Session::all();

                $inventory = Inventory::with(['product'])
                    ->whereHas('product', function (Builder $query) use ($user) {
                        $query->where('admin_id', '=', $user->id);
                    })
                    ->where(function ($query) use ($user, $session) {
                        $query->where('sku', 'LIKE', '%' . $session['query'] . '%');
                        $query->orWhereHas('product', function (Builder $query) use ($user, $session) {
                            $query->where('id', '=', $session['query']);
                        });
                    })
                    ->where('quantity', '<=', $session['quantity_limit'])
                    ->paginate(50);

            } else {

                $inventory = Inventory::with(['product'])
                    ->whereHas('product', function (Builder $query) use ($user) {
                        $query->where('admin_id', '=', $user->id);
                    })
                    ->paginate(50);

            }

            $allInventory = Inventory::with(['product'])
                ->select('price_cents', 'cost_cents', 'quantity')
                ->whereHas('product', function (Builder $query) use ($user) {
                    $query->where('admin_id', '=', $user->id);
                })
                ->get();

            return view('dashboard.inventory.home')
                ->with(compact([
                    'user',
                    'inventory',
                    'allInventory'
                ]));

        } catch (\Exception $e) {

            dd($e);
            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }

    }

    /**
     * Method used to process a search request to filter Inventory view
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function search(Request $request)
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            $request->session()->forget(['query', 'quantity_limit']);

            $inventory = Inventory::with(['product'])
                ->whereHas('product', function (Builder $query) use ($user, $request) {
                    $query->where('admin_id', '=', $user->id);
                })
                ->where(function ($query) use ($user, $request) {
                    $query->where('sku', 'LIKE', '%' . $request->input('query') . '%');
                    $query->orWhereHas('product', function (Builder $query) use ($user, $request) {
                        $query->where('id', '=', $request->input('query'));
                    });
                })
                ->where('quantity', '<=', $request->quantity_limit)
                ->paginate(50);

            $allInventory = Inventory::with(['product'])
                ->select('price_cents', 'cost_cents', 'quantity')
                ->whereHas('product', function (Builder $query) use ($user) {
                    $query->where('admin_id', '=', $user->id);
                })
                ->get();

            $request->session()->put('query', $request->input('query'));
            $request->session()->put('quantity_limit', $request->input('quantity_limit'));

            return view('dashboard.inventory.home')
                ->with(compact([
                    'user',
                    'inventory',
                    'allInventory'
                ]));

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Inventory  $inventory
     * @return \Illuminate\Http\Response
     */
    public function show(Inventory $inventory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Inventory  $inventory
     * @return \Illuminate\Http\Response
     */
    public function edit(Inventory $inventory)
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            return view('dashboard.inventory.edit')
                ->with(compact([
                    'user',
                    'inventory',
                ]));

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Inventory  $inventory
     * @return \Illuminate\Http\Response
     */
    public function update(InventoryUpdateRequest $request, Inventory $inventory)
    {
        try {

            $inventory->quantity = $request->quantity;
            $inventory->color = $request->color;
            $inventory->size = $request->size;
            $inventory->weight = $request->weight;
            $inventory->price_cents = $this->removeUsdFormatStyling($request->price) * 100;
            $inventory->sale_price_cents = $this->removeUsdFormatStyling($request->sale_price) * 100;
            $inventory->cost_cents = $this->removeUsdFormatStyling($request->cost) * 100;
            $inventory->length = $request->length;
            $inventory->width = $request->width;
            $inventory->height = $request->height;
            $inventory->note = empty($request->note) ? null : $request->note;
            $inventory->save();

            return redirect()
                ->route('dashboard.inventory.home')
                ->with('success', 'Successfully updated inventory.');

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Inventory  $inventory
     * @return \Illuminate\Http\Response
     */
    public function destroy(Inventory $inventory)
    {
        try {

            $user = Auth::user();

            // todo - Validate that User is Auth
            // todo - validate that Auth user can delete product

            $inventory->delete();

            return redirect()->route('dashboard.inventory.home')
                ->with('success', 'Successfully deleted inventory.');

        } catch (\Exception $e) {

            Log::error($e);
            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    // todo - This should be a global utility
    private function removeUsdFormatStyling($amountStringValue)
    {

        return empty($amountStringValue) ? '0.00' : preg_replace('/[^0-9\.]/', '', $amountStringValue);

    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/BootstrapAppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BootstrapAppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.bootstrap-app');
    }
}

resources/views/dashboard/inventory/home.blade.php
<x-bootstrap-app-layout>
    <x-slot name="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">{{ __('Inventory') }} Page {{ $inventory->currentPage() }}/{{ $inventory->lastPage() }}</li>
    </x-slot>
    <x-slot name="header">Inventory</x-slot>
    <x-slot name="content">
        <section>
            <div class="row">
                <div class="col-md-12">
                    <div class="row mb-5 mt-5">
                        <div class="col-md-12">
                            <h3>At a Glance</h3>
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="card">
                                        <div class="card-header">
                                            Total Unique Inventory Records
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-title">{{ $allInventory->count() }} Records</h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="card">
                                        <div class="card-header">
                                            Total Inventory Quantity
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-title">{{ $allInventory->sum('quantity') }} pieces</h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="card">
                                        <div class="card-header">
                                            Avg. Item Price
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-title">{{ \App\Models\Product::convertToUsDollars($allInventory->avg('price_cents')) }}</h4>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="card">
                                        <div class="card-header">
                                            Avg. Item Cost
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-title">{{ \App\Models\Product::convertToUsDollars($allInventory->avg('cost_cents')) }}</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-5">
                        <div class="col">
                            <form class="row g-3 align-items-center" method="POST" action="{{ route('dashboard.inventory.search') }}" class="">
                                @csrf
                                <div class="col-md-6">
                                    <label for="query" class="visually-hidden">Search by Product ID or Inventory SKU</label>
                                    <input type="text" class="form-control @error('query') is-invalid @enderror" id="query" name="query" value="{{ old('query', (!empty(\Illuminate\Support\Facades\Session::get('query')) ? \Illuminate\Support\Facades\Session::get('query') : '')) }}" placeholder="Search by Product ID or Inventory SKU" />
                                    @error('query')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="col-md-3">
                                    <label for="quantity_limit" class="form-label">Show Items with quantities less than <strong><span id="qty-slider-value"></span></strong></label>
                                    <input type="range" class="form-range" min="0" max="{{ $allInventory->max('quantity') }}" id="quantity_limit" name="quantity_limit" value="{{ old('quantity_limit', (!empty(\Illuminate\Support\Facades\Session::get('quantity_limit')) ? \Illuminate\Support\Facades\Session::get('quantity_limit') : $allInventory->max('quantity'))) }}">
                                </div>
                                <div class="col-2">
                                    <button type="submit" class="btn btn-primary">Search</button>
                                    <a href="{{ route('dashboard.inventory.home', ['reset' => 'reset']) }}" class="btn btn-danger">Reset</a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col">
                            <h2>Results: {{ $inventory->total() }} Items</h2>
                            @if(!empty(\Illuminate\Support\Facades\Session::get('quantity_limit')))
                                <a href="{{ route('dashboard.inventory.home', ['reset' => 'reset']) }}" class="btn btn-sm btn-danger">Reset Search Results</a>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover">
                                <thead>
                                <th>Product ID</th>
                                <th>Product Name</th>
                                <th>SKU</th>
                                <th>Quantity</th>
                                <th>Color</th>
                                <th>Size</th>
                                <th>Price</th>
                                <th>Cost</th>
                                <th>Actions</th>
                                </thead>
                                <tbody>
                                @foreach($inventory as $item)
                                    <tr>
                                        <td>{{ $item->product->id }}</td>
                                        <td>{{ $item->product->name }}</td>
                                        <td>{{ $item->sku }}</td>
                                        <td>{{ $item->quantity }}</td>
                                        <td>{{ $item->color }}</td>
                                        <td>{{ $item->size }}</td>
                                        <td>{{ \App\Models\Product::convertToUsDollars($item->price_cents) }}</td>
                                        <td>{{ \App\Models\Product::convertToUsDollars($item->cost_cents) }}</td>
                                        <td>
                                            <div class="row m-1">
                                                <div class="col">
                                                    <a href="{{ route('dashboard.inventory.edit', ['inventory' => $item->id]) }}" class="btn btn-sm btn-warning">Edit</a>
                                                </div>
                                            </div>
                                            <div class="row m-1">
                                                <div class="col">
                                                    <form class="row" method="POST" action="{{ route('dashboard.inventory.delete', ['inventory' => $item->id]) }}" class="">
                                                        @csrf
                                                        {{method_field('DELETE')}}
                                                        <div class="col-2">
                                                            <input type="hidden" name="inventory_id" value="{{ $item->id }}" />
                                                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <nav class="pagination" aria-label="Page navigation example">
                                <ul class="pagination">
                                    <li class="page-item {{ ($inventory->currentPage() == 1) ? ' disabled' : '' }}">
                                        @if($inventory->currentPage() == 1)
                                            <a href="#" onclick="return false;" class="page-link">Previous</a>
                                        @else
                                            <a href="{{ $inventory->url(1) }}" class="page-link">Previous</a>
                                        @endif
                                    </li>
                                    @for ($i = 1; $i <= $inventory->lastPage(); $i++)
                                        <li class="page-item {{ ($inventory->currentPage() == $i) ? ' active' : '' }}">
                                            <a href="{{ route('dashboard.inventory.home', ['page' => $i]) }}" class="page-link">{{ $i }}</a>
                                        </li>
                                    @endfor
                                    <li class="page-item {{ ($inventory->currentPage() == $inventory->lastPage()) ? ' disabled' : '' }}">
                                        @if($inventory->currentPage() == $inventory->lastPage())
                                            <a href="#" onclick="return false;" class="page-link">Next</a>
                                        @else
                                            <a href="{{ $inventory->url($inventory->currentPage()+1) }}" class="page-link" >Next</a>
                                        @endif
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </x-slot>
    <x-slot name="scripts">
        <script>
            $(document).ready(function(){

                // On Load
                updateRangeCurrentValue();

                $('input#quantity_limit').change(function(){
                    updateRangeCurrentValue()
                });

            });

            function updateRangeCurrentValue()
            {

                var value = $('input#quantity_limit').val();

                $('span#qty-slider-value').html(value)

            }
        </script>
    </x-slot>
</x-bootstrap-app-layout>