routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome-bootstrap');
});
Route::get('/welcome-default', function () {
    return view('welcome');
});

Route::prefix('dashboard')->name('dashboard.')->middleware(['auth'])->group(function () {
    Route::get('/', [\App\Http\Controllers\DashboardController::class, 'index'])->name('home');

    Route::prefix('product')->name('product.')->group(function () {
        Route::get('/', [\App\Http\Controllers\ProductController::class, 'index'])->name('home');
        Route::get('/create', [\App\Http\Controllers\ProductController::class, 'create'])->name('create');
        Route::post('/store', [\App\Http\Controllers\ProductController::class, 'store'])->name('store');
        Route::prefix('{product}')->group(function () {
            Route::get('/', [\App\Http\Controllers\ProductController::class, 'show'])->name('show');
            Route::get('/edit', [\App\Http\Controllers\ProductController::class, 'edit'])->name('edit');
            Route::put('/edit', [\App\Http\Controllers\ProductController::class, 'update'])->name('update');
            Route::delete('/delete', [\App\Http\Controllers\ProductController::class, 'destroy'])->name('delete');
            Route::get('/create-inventory', [\App\Http\Controllers\ProductController::class, 'createInventory'])->name('create-inventory');
            Route::post('/store-inventory', [\App\Http\Controllers\ProductController::class, 'storeInventory'])->name('store-inventory');
        });
    });

    Route::prefix('inventory')->name('inventory.')->group(function () {
        Route::get('/{reset?}', [\App\Http\Controllers\InventoryController::class, 'index'])->name('home');
        Route::post('/', [\App\Http\Controllers\InventoryController::class, 'search'])->name('search');
        Route::post('/reset', [\App\Http\Controllers\InventoryController::class, 'searchReset'])->name('search-reset');
        Route::prefix('{inventory}')->group(function () {
            Route::get('/edit', [\App\Http\Controllers\InventoryController::class, 'edit'])->name('edit');
            Route::put('/edit', [\App\Http\Controllers\InventoryController::class, 'update'])->name('update');
            Route::delete('/delete', [\App\Http\Controllers\InventoryController::class, 'destroy'])->name('delete');
        });
    });

});

require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public function skus()
    {

        return $this->hasMany(
            Inventory::class,
            'product_id',
            'id'
        );

    }

    // todo - Should be a global utility
    public static function convertToUsDollars($cents = 0)
    {

        $fmt = numfmt_create( 'en_US', \NumberFormatter::CURRENCY);
        return numfmt_format_currency($fmt, ($cents / 100), "USD");

    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            return view('dashboard.home')
                ->with(
                    compact(
                        [
                            'user'
                        ]
                    )
                );

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Dpaz\SymCrypt;
use App\Http\Requests\OrderHistoryStoreRequest;
use App\Http\Requests\ProductInsertRequest;
use App\Http\Requests\ProductInventoryInsertRequest;
use App\Http\Requests\ProductUpdateRequest;
use App\Models\Inventory;
use App\Models\Order;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            $products = Product::with(['skus'])
                ->where('admin_id', '=', $user->id)
                ->paginate(25);

            return view('dashboard.products.home')
                ->with(compact([
                    'user',
                    'products',
                ]));

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            return view('dashboard.products.create')
                ->with(compact([
                    'user'
                ]));

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Method used to display a form used to create Inventory in the context of a Product
     *
     * @param Product $product
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function createInventory(Product $product)
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            return view('dashboard.products.create-product-inventory')
                ->with(compact([
                    'user',
                    'product'
                ]));

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductInsertRequest $request)
    {
        try {

            $product = new Product();
            $product->name = $request->name;
            $product->admin_id = Auth::user()->id;
            $product->description = $request->description;
            $product->style = $request->style;
            $product->brand = $request->brand;
            $product->type = $request->type;
            $product->shipping_price = $this->removeUsdFormatStyling($request->shipping_price) * 100; // Change to USD cents
            $product->note = empty($request->note) ? null : $request->note;
            $product->url = empty($request->url) ? null : $request->url;
            $product->save();

            return redirect()
                ->route('dashboard.product.show', ['product' => $product->id])
                ->with('success', 'Successfully created product.');

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Method used to store inventory in the context of a given Product
     *
     * @param ProductInventoryInsertRequest $request
     * @param Product $product
     * @return \Illuminate\Http\RedirectResponse
     */
    public function storeInventory(ProductInventoryInsertRequest $request, Product $product)
    {
        try {

            $inventory = new Inventory();
            $inventory->product_id = $product->id;
            $inventory->sku = $request->sku;
            $inventory->quantity = $request->quantity;
            $inventory->color = $request->color;
            $inventory->size = $request->size;
            $inventory->weight = $request->weight;
            $inventory->price_cents = $this->removeUsdFormatStyling($request->price) * 100;
            $inventory->sale_price_cents = $this->removeUsdFormatStyling($request->sale_price) * 100;
            $inventory->cost_cents = $this->removeUsdFormatStyling($request->cost) * 100;
            $inventory->length = $request->length;
            $inventory->width = $request->width;
            $inventory->height = $request->height;
            $inventory->note = empty($request->note) ? null : $request->note;
            $inventory->save();

            return redirect()
                ->route('dashboard.product.show', ['product' => $product->id])
                ->with('success', 'Successfully created inventory for product.');

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            return view('dashboard.products.show')
                ->with(compact([
                    'user',
                    'product',
                ]));

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        try {

            if(!Auth::check()) {

                throw new \Exception('User Authentication required.');

            }

            $user = Auth::user();

            return view('dashboard.products.edit')
                ->with(compact([
                    'user',
                    'product',
                ]));

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductUpdateRequest $request, Product $product)
    {
        try {

            $product->name = $request->name;
            $product->description = $request->description;
            $product->style = $request->style;
            $product->brand = $request->brand;
            $product->type = $request->type;
            $product->shipping_price = $this->removeUsdFormatStyling($request->shipping_price) * 100; // Change to USD cents
            $product->note = empty($request->note) ? null : $request->note;
            $product->url = empty($request->url) ? null : $request->url;
            $product->save();

            return redirect()
                ->route('dashboard.product.show', ['product' => $product->id])
                ->with('success', 'Successfully updated product.');

        } catch (\Exception $e) {

            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        try {

            $user = Auth::user();

            // todo - Validate that User is Auth
            // todo - validate that Auth user can delete product

            $product->delete();

            return redirect()->route('dashboard.product.home')
                ->with('success', 'Successfully deleted product.');

        } catch (\Exception $e) {

            Log::error($e);
            return redirect()->back()->withErrors(['errors' => $e->getMessage()]);

        }
    }

    // todo - This should be a global utility
    private function removeUsdFormatStyling($amountStringValue)
    {

        return empty($amountStringValue) ? '0.00' : preg_replace('/[^0-9\.]/', '', $amountStringValue);

    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/BootstrapAppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BootstrapAppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.bootstrap-app');
    }
}

resources/views/dashboard/products/home.blade.php
<x-bootstrap-app-layout>
    <x-slot name="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">{{ __('Products') }} Page {{ $products->currentPage() }}/{{ $products->lastPage() }}</li>
    </x-slot>
    <x-slot name="header">Products</x-slot>
    <x-slot name="content">
        <section>
            <div class="row mt-5">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col">
                            <a href="{{ route('dashboard.product.create') }}" class="btn btn btn-success">Create New Product</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover">
                                <thead>
                                <th>Product ID</th>
                                <th>Name</th>
                                <th>Brand</th>
                                <th>Style</th>
                                <th>SKUs</th>
                                <th>Actions</th>
                                </thead>
                                <tbody>
                                @foreach($products as $product)
                                    <tr>
                                        <td>{{ $product->id }}</td>
                                        <td>{{ $product->name }}</td>
                                        <td>{{ $product->brand }}</td>
                                        <td>{{ $product->style }}</td>
                                        <td>
                                            <ul>
                                                @foreach($product->skus as $sku)
                                                    <li>{{ $sku->sku }}</li>
                                                @endforeach
                                            </ul>
                                        </td>
                                        <td>
                                            <div class="row m-1">
                                                <div class="col">
                                                    <a href="{{ route('dashboard.product.show', ['product' => $product->id]) }}" class="btn btn-sm btn-warning">View</a>
                                                </div>
                                            </div>
                                            <div class="row m-1">
                                                <div class="col">
                                                    <form class="row" method="POST" action="{{ route('dashboard.product.delete', ['product' => $product->id]) }}" class="">
                                                        @csrf
                                                        {{method_field('DELETE')}}
                                                        <div class="col-2">
                                                            <input type="hidden" name="product_id" value="{{ $product->id }}" />
                                                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <nav class="pagination" aria-label="Page navigation example">
                                <ul class="pagination">
                                    <li class="page-item {{ ($products->currentPage() == 1) ? ' disabled' : '' }}">
                                        @if($products->currentPage() == 1)
                                            <a href="#" onclick="return false;" class="page-link">Previous</a>
                                        @else
                                            <a href="{{ $products->url(1) }}" class="page-link">Previous</a>
                                        @endif
                                    </li>
                                    @for ($i = 1; $i <= $products->lastPage(); $i++)
                                        <li class="page-item {{ ($products->currentPage() == $i) ? ' active' : '' }}">
                                            <a href="{{ $products->url($i) }}" class="page-link">{{ $i }}</a>
                                        </li>
                                    @endfor
                                    <li class="page-item {{ ($products->currentPage() == $products->lastPage()) ? ' disabled' : '' }}">
                                        @if($products->currentPage() == $products->lastPage())
                                            <a href="#" onclick="return false;" class="page-link">Next</a>
                                        @else
                                            <a href="{{ $products->url($products->currentPage()+1) }}" class="page-link" >Next</a>
                                        @endif
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </x-slot>
</x-bootstrap-app-layout>

resources/views/dashboard/products/show.blade.php
<x-bootstrap-app-layout>
    <x-slot name="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.product.home') }}">{{ __('Products') }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ __('Product: ') }} {{ $product->name }}</li>
    </x-slot>
    <x-slot name="header">Product</x-slot>
    <x-slot name="content">
        <section class="mb-5">
            <div class="row">
                <div class="col-md-12">
                    <h2>Product: {{ $product->name }}</h2>
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover">
                                <thead>
                                <th>Product ID</th>
                                <th>Name</th>
                                <th>Brand</th>
                                <th>Shipping Price</th>
                                <th>Style</th>
                                <th>URL</th>
                                <th>Actions</th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>{{ $product->id }}</td>
                                        <td>{{ $product->name }}</td>
                                        <td>{{ $product->brand }}</td>
                                        <td>{{ \App\Models\Product::convertToUsDollars($product->shipping_price) }}</td>
                                        <td>{{ $product->style }}</td>
                                        <td>{{ $product->url }}</td>
                                        <td>
                                            <div class="row m-1">
                                                <div class="col">
                                                    <a href="{{ route('dashboard.product.edit', ['product' => $product->id]) }}" class="btn btn-sm btn-warning">Edit</a>
                                                </div>
                                            </div>
                                            <div class="row m-1">
                                                <div class="col">
                                                    <form class="row" method="POST" action="{{ route('dashboard.product.delete', ['product' => $product->id]) }}" class="">
                                                        @csrf
                                                        {{method_field('DELETE')}}
                                                        <div class="col-2">
                                                            <input type="hidden" name="product_id" value="{{ $product->id }}" />
                                                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <h3>Description</h3>
                    <p>{{ $product->description }}</p>
                </div>
                @if(!empty($product->note))
                    <div class="col-md-12">
                        <h3>Note</h3>
                        <p>{{ $product->note }}</p>
                    </div>
                @endif
            </div>
        </section>
        <section>
            <div class="row">
                <div class="col-md-12">
                    <h2>Product Inventory</h2>
                    <div class="row">
                        <div class="col">
                            <a href="{{ route('dashboard.product.create-inventory', ['product' => $product->id]) }}" class="btn btn btn-success">Create New Inventory</a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover">
                                <thead>
                                <th>SKU</th>
                                <th>Quantity</th>
                                <th>Color</th>
                                <th>Size</th>
                                <th>Weight</th>
                                <th>Price</th>
                                <th>Sale Price</th>
                                <th>Cost</th>
                                <th>Length</th>
                                <th>Width</th>
                                <th>Height</th>
{{--                                <th>Actions</th>--}}
                                </thead>
                                <tbody>
                                @foreach($product->skus as $inventory)
                                    <tr>
                                        <td>{{ $inventory->sku }}</td>
                                        <td>{{ $inventory->quantity }}</td>
                                        <td>{{ $inventory->color }}</td>
                                        <td>{{ $inventory->size }}</td>
                                        <td>{{ $inventory->weight }}</td>
                                        <td>{{ \App\Models\Product::convertToUsDollars($inventory->price_cents) }}</td>
                                        <td>{{ \App\Models\Product::convertToUsDollars($inventory->sale_price_cents) }}</td>
                                        <td>{{ \App\Models\Product::convertToUsDollars($inventory->cost_cents) }}</td>
                                        <td>{{ $inventory->length }}</td>
                                        <td>{{ $inventory->width }}</td>
                                        <td>{{ $inventory->height }}</td>
{{--                                        <td></td>--}}
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </x-slot>
</x-bootstrap-app-layout>